# Generated by Django 5.2.17 on 2026-08-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DismissedFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_id', models.IntegerField(unique=True)),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
