# Generated by Django 5.2.17 on 2026-09-04 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DismissedFailure',
        ),
    ]
