# Generated by Django 5.2.17 on 2026-09-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0004_alter_vm_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='image_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vm',
            name='image_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
