# Generated by Django 5.2.17 on 2026-09-04 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0005_vm_image_id_vm_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleanup_status', models.CharField(choices=[('CLEANED', 'CLEANED'), ('CLEANUP_FAILED', 'CLEANUP_FAILED')], max_length=16)),
                ('cleanup_error', models.TextField(blank=True, default='')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('vm', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='failure', to='provisioning.vm')),
            ],
        ),
    ]
