# Generated by Django 5.2.17 on 2026-09-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('base_image_id', models.UUIDField()),
                ('base_image_name', models.CharField(max_length=255)),
                ('server_id', models.UUIDField(blank=True, null=True)),
                ('glance_image_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CREATING', '제작 VM 생성 중'), ('READY', '설정 가능'), ('SNAPSHOTTING', '이미지 생성 중'), ('PUBLISHED', '사용 가능'), ('FAILED', '실패')], default='CREATING', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
