# Generated by Django 5.2.17 on 2026-09-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagebuild', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebuild',
            name='status',
            field=models.CharField(choices=[('CREATING', '제작 환경 준비 중'), ('READY', '설정 가능'), ('SNAPSHOTTING', '이미지 생성 중'), ('CANCELING', '제작 취소 중'), ('CANCELED', '제작 취소'), ('PUBLISHED', '사용 가능'), ('FAILED', '실패')], default='CREATING', max_length=20),
        ),
    ]
